### ISSUE TITLE
cannot import name 'HunyuanVideo' from 'comfy.model_base' (F:\ComfyUI\ComfyUI\comfy\model_base.py)

### ISSUE THREAD

**Issue by xueqing0622** [pamparamm/ComfyUI-ppm#17]
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-ppm\__init__.py", line 4, in <module>
    from .nodes.clip_negpip import CLIPNegPip
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-ppm\nodes\clip_negpip.py", line 9, in <module>
    from comfy.model_base import Flux, HunyuanVideo
ImportError: cannot import name 'HunyuanVideo' from 'comfy.model_base' (F:\ComfyUI\ComfyUI\comfy\model_base.py)

Cannot import F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-ppm module for custom nodes: cannot import name 'HunyuanVideo' from 'comfy.model_base' (F:\ComfyUI\ComfyUI\comfy\model_base.py)

**Comment by pamparamm** [comment]
HunyuanVideo class was added very recently, are you using latest ComfyUI version?

**Comment by xueqing0622** [comment]
yes, the latest comfyui version

**Comment by PyrateGFXProductions** [comment]
ok, so it is not just me.

**Comment by pamparamm** [comment]
Oh, I meant latest commit, not version - my bad.
The latest commit of ComfyUI contains HunyuanVideo (and I've tested NegPip+HunyuanVideo on a pure ComfyUI installation together with ComfyUI-ppm), perhaps you haven't pulled recent changes.

I've added a temporary fallback for people that use stable version of ComfyUI instead of a rolling version - that should fix this problem.

**Comment by xueqing0622** [comment]
thx your answer pamparamm, the ppm nodes is so cool, and the Schedulers of  AYS_30 has very good effect for image!

**Comment by xueqing0622** [comment]
btw, which commit of comfyui I should rolling back!

**Comment by xueqing0622** [comment]
I rolling back a lot of commit and version, still not work,  maybe crash by other requirements.
